const API_URL = import.meta.env.VITE_APP_API_URL;
const METABASE_API_URL = import.meta.env.VITE_APP_METABASE_API_URL;
const METABASE_API_KEY = import.meta.env.VITE_APP_METABASE_API_KEY;

export { API_URL, METABASE_API_URL, METABASE_API_KEY };