name: Deploy Vue

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      VITE_APP_API_URL: ${{ secrets.VITE_APP_API_URL }}
      VITE_APP_METABASE_API_URL: ${{ secrets.VITE_APP_METABASE_API_URL }}
      VITE_APP_METABASE_API_KEY: ${{ secrets.VITE_APP_METABASE_API_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies and build
        run: |
          npm install
          npm run build

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp -r dist/* ./deploy/

      - name: Copy files via SCP
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "deploy/*"
          target: "/var/www/vue-app"
